name: Run Tests
run-name: ${{ github.actor }} is ${{ github.workflow }}
on:
  push:
    branches: [develop, tests]
jobs:
  tests_on_windows:
    name: Tests on Windows
    runs-on: [self-hosted, Windows]
    if: ${{ vars.ENABLE_WINDOWS_RUNNER == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          clean: false

      - name: PlayMode Tests
        shell: cmd
        run: |
          "${{ vars.PROJECT_DIR_NAME && format('{0}\', vars.PROJECT_DIR_NAME) || '' }}tools\cicd\tests\run_tests.bat" PlayMode Project.Tests
          if %ERRORLEVEL% neq 0 exit /b %ERRORLEVEL%

  tests_on_macos:
    name: Tests on macOS
    runs-on: [self-hosted, macOS]
    if: ${{ vars.ENABLE_MACOS_RUNNER == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          clean: false

      - name: PlayMode Tests
        shell: bash
        run: |
          "${{ vars.PROJECT_DIR_NAME && format('{0}/', vars.PROJECT_DIR_NAME) || '' }}tools/cicd/tests/run_tests.command" PlayMode Project.Tests
          if [ $? -ne 0 ]; then exit 1; fi

