name: Run Tests
run-name: ${{ github.actor }} is ${{ github.workflow }} ${{ vars.PROJECT_DIR_NAME }}
on:
  push:
    branches: [develop, tests]
jobs:
  Tests:
    strategy:
      matrix:
        include:
          - os: Windows
            runs-on: [self-hosted, Windows]
            enable_var: ENABLE_WINDOWS_RUNNER
          - os: macOS
            runs-on: [self-hosted, macOS]
            enable_var: ENABLE_MACOS_RUNNER
    runs-on: ${{ matrix.runs-on }}
    if: ${{ vars[matrix.enable_var] == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          clean: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: PlayMode Tests (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          "${{ vars.PROJECT_DIR_NAME && format('{0}\', vars.PROJECT_DIR_NAME) || '' }}tools\cicd\tests\run_tests.bat" PlayMode Project.Tests
          if %ERRORLEVEL% neq 0 exit /b %ERRORLEVEL%

      - name: PlayMode Tests (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          "${{ vars.PROJECT_DIR_NAME && format('{0}/', vars.PROJECT_DIR_NAME) || '' }}tools/cicd/tests/run_tests.command" PlayMode Project.Tests
          if [ $? -ne 0 ]; then exit 1; fi

