name: Run Tests
run-name: ${{ github.actor }} is $GITHUB_ACTION
on:
  push:
    branches: [develop]
jobs:
  Tests:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          clean: false

      - name: PlayMode Tests
        shell: cmd
        run: |
          "${{ env.PROJECT_DIR_NAME }}/tools/cicd/tests/run_test.bat" PlayMode Project.Tests

